#!/bin/sh
if [ $# -lt 2 ]; then
	echo 'UNKNOWN: usage: $0 warnSYSIOWThesh critSYSIOThresh [perfdata]'
	exit 3
fi

if [ $1 -gt $2 ]; then
	echo 'UNKNOWN: warning, warningThreshold > criticalThreshold'
	exit 3
fi

send_perf_data=0
if [ $# -gt 2 ]; then
	send_perf_data=$(($3 + 0))
fi

case `uname` in
	AIX)
		fields=`vmstat 1 1 | tail -1 | tr -s ' '`
		pct_us=`echo "$fields" | cut -d ' ' -f 15`
		pct_sy=`echo "$fields" | cut -d ' ' -f 16`
		pct_id=`echo "$fields" | cut -d ' ' -f 17`
		pct_wa=`echo "$fields" | cut -d ' ' -f 18`
		fields=`echo "$fields" | cut -d ' ' -f 16,18`
	;;
	Linux)
		fields=`vmstat 1 2 | tail -1 | tr -s ' '`
		pct_us=`echo "$fields" | cut -d ' ' -f 14`
		pct_sy=`echo "$fields" | cut -d ' ' -f 15`
		pct_id=`echo "$fields" | cut -d ' ' -f 16`
		pct_wa=`echo "$fields" | cut -d ' ' -f 17`
		fields=`echo "$fields" | cut -d ' ' -f 15,17`
	;;
	SunOS)
		fields=`iostat -c 1 2 | tail -1 | tr -s ' ' | cut -d ' ' -f 3,4`
	;;
	*)
		echo "UNKNOWN: don't know how to get CPU usage on `uname`"
		exit 3
	;;
esac

f1=`echo $fields | cut -d ' ' -f1`
f2=`echo $fields | cut -d ' ' -f2`
sum=`expr $f1 + $f2`
msg="System+IOWait CPU usage is $sum% (warn = $1%, crit = $2%)"

if ( test -n "$pct_wa" -a $send_perf_data -gt 0 ); then
	msg="$msg|User=$pct_us%;;;; Kernel=$pct_sy%;;;; Idle=$pct_id%;;;; Wait=$pct_wa%;;;;"
fi

if [ $sum -ge $2 ]; then
	echo "CRITICAL: $msg"
	exit 2
fi

if [ $sum -ge $1 ]; then
	echo "WARNING: $msg"
	exit 1
fi

echo "OK: $msg"
exit 0
